### ISSUE TITLE
MarcoT: Definiciones y decisiones sobre Moodle

### ISSUE THREAD

**Issue by DanielOrtegaZ** [RicardoPolit/gamificationTT#5]
Poner las siguientes cosas en el Marco Teorico
- [x] Definiciones de *Logros, Experiencia, Niveles y demás* relevantes al **Modulo de Experiencia**
- [x] **Marco Teórico** -> **Sistemas Gestores de Aprendizaje**: Referenciar las citas donde mencionan por que escojer *Moodle* (Movido a otro **issue #22 **)
- [x] **Marco Teorico** -> **Moodle**: Describir opciones para extender/agregar nuevas funcionalidades en Moodle, ¿Porqué desarrollar plugins? (Movido a issue #23 )

**Comment by RicardoPolit** [comment]
Para mi ese issue son tres, porque si pones un issue que se llama Marco Teórico es demasiado general. @DanielOrtegaZ

**Comment by DanielOrtegaZ** [comment]
Se que podrían ir separados en 3 issues pero tambien descubri que si se pone una lista las tareas se pueden palomear conforme vayan siendo completadas, y cuando las 3 estén listas se libera el issue completo
@RicardoPolit

**Comment by RicardoPolit** [comment]
Si pero entonces van a existir varios issues con el mismo nombre, a eso me refería.
@DanielOrtegaZ

**Comment by DanielOrtegaZ** [comment]
@RicardoPolit  nombre cambiado
